### ISSUE TITLE
Extra padding at bottom of WebView

### ISSUE THREAD

**Issue by erfz** [sidvenu/MathJaxView#2]
I have the MathJaxView inside a LinearLayout, which is inside a NestedScrollView.
When the MathJaxView is large enough that I need to scroll to get to the bottom of it, there is extra padding at the bottom. There seems to be the correct amount of padding everywhere else, though.

Could you look into this? I suspect it has to do with your mathjax config -- this issue isn't present in kexanies mathview.

**Comment by sidvenu** [comment]
I had the same problem too. It has something to do with the display mode of MathJax. MathJax leaves an empty line in the bottom whenever you use $$ $$ style. 

Try using $ $ style if you don't want the empty line (and set the gravity of the mathjaxview to center if you need it to be). I have used that style and noticed very little difference except it doesn't leave an empty line at the bottom.

I think kexanie's MathView doesn't have this problem since it uses a pretty old version of MathJax and MathJax is usually actively updated to improve the UI. I guess the old MathJax doesn't leave a trailing empty line.

Let me know if the above works for you so that I can close this issue. (Or if you think I am wrong)

**Comment by erfz** [comment]
Ah I see. What release of MathJax did you use here?

**Comment by sidvenu** [comment]
MathJax v2.7.2. Will be updating to 2.7.3 soon when I have the time

**Comment by sidvenu** [comment]
I am closing this issue now. If you feel something can be done to remove the bottom padding (which I don't think it can be) then reopen it with more information.

**Comment by sidvenu** [comment]
a8e9939cc95faa5b5970792dd366912fa3c66a77 fixes #2
